### PR TITLE
Weatherlogging degree symbol

### PR DESCRIPTION
**Pull request by Romfrosk**
## Description
Change misspelled "Degreese" to ° in weather logging

## Motivation and Context
Logging had a typo, and changed to degree symbol instead

## How Has This Been Tested?
Tested on dev setup

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rlodev67** [comment]
Can you change it to log.debug too ?

**Comment by Romfrosk** [comment]
Moved to debug logging :)

**Comment by Greenwardog** [comment]
works correctly

**Comment by rlodev67** [comment]
Please change it to dev branch

**Comment by whitewillem** [comment]
Running this for a while now. Does what it should do.

**Comment by rlodev67** [comment]
thanks

**Pull request merged**
