### PR TITLE
API 0.91.2

### PR DESCRIPTION
**Pull request by tokar86a**
New API version.

### CODE REVIEW

**Comment by The-Real-Ketchum-Dev** [comment]
still not working.. Have you tested?

**Comment by tokar86a** [comment]
The problem is that the API have changed but not the app version. I think that is the problem.

**Comment by whitewillem** [comment]
9102:9100 needs to be added to runserver.py

**Comment by tokar86a** [comment]
still seems like something more needs to be added.

**Comment by The-Real-Ketchum-Dev** [comment]
works needs merged

**Comment by whitewillem** [comment]
Tested, works fine. Please merge it.

**Comment by RedFirebreak** [comment]
Tested, works

**Pull request merged**
