### PR TITLE
Added Taillow as ditto

### PR DESCRIPTION
**Pull request by tokar86a**
https://youtu.be/g3rmnMNnddQ?t=8m19s

### CODE REVIEW

**Comment by whitewillem** [comment]
This could be becouse its a event. I think we should wait until its over and then check if there are new options.

**Comment by SkOODaT** [comment]
ive been catching Taillow on my map with gain-xp not even 1 ditto seen since friday~

**Comment by darkelement1987** [comment]
No taillow-dittos here as well

**Comment by darkelement1987** [comment]
Update: During the event no taillows have shown up as Ditto

**Pull request closed without merging**
