### PR TITLE
Add Prio Notify switch

### PR DESCRIPTION
**Pull request by cecpk**
## Description
Switch Prio Notify to on: Pokemons will shown on the map, even they are hidden through filters. 

## Motivation and Context
Never miss a good Pokemon just because of a filter

## How Has This Been Tested?
own Fork

## Screenshots (if appropriate):
screenshot 2018-03-03 um 18 07 40

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project. (I think so :))
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by whitewillem** [comment]
Using this for a few days now. Works great. I like it.

**Comment by Deewii** [comment]
Does not work well here.
At first it seemed fine, but after trying different options it's stuck on always notifying.
Hide a certain pokémon, Prio notify off, and still get notifications of it.

**Comment by cecpk** [comment]
Could you give me a special example. Never been on my map. Aber f5 refresh?

**Comment by Deewii** [comment]
bild

**Comment by Deewii** [comment]
Gastly is hidden, this is a screenshot after a refresh.

**Comment by cecpk** [comment]
Dont see my Switch of this PR?!

**Comment by Deewii** [comment]
Oh sorry, I just renamed it to Notify Hidden in map.html

**Comment by cecpk** [comment]
Ok ;). Let me check this

**Comment by cecpk** [comment]
Found the error! Please test again. Thx

**Comment by Deewii** [comment]
Tested and is working as intended 👍

**Comment by cecpk** [comment]
Any other experience?

**Comment by rlodev67** [comment]
sounds good, but change it to dev branch plz

**Comment by darkelement1987** [comment]
Is this ready for merge?

**Comment by darkelement1987** [comment]
I would suggest using 'Notify hidden' as well.

**Comment by OfficialWiddin** [comment]
"Notify Hidden" sounds more explaining than "Prio Notify".

**Pull request merged**
