### PR TITLE
Added support for catch probs, atk-def rating

### PR DESCRIPTION
**Pull request by rlodev67**
## Description

Added support for stock PA
## Motivation and Context

Have a working webhook with stock PA
## How Has This Been Tested?

@whitewillem  tested it

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by darkelement1987** [comment]
Doesn't this need editing in `app.py` as well?

**Comment by rlodev67** [comment]
No cause nothing more is inserted in DB

**Comment by The-Real-Ketchum-Dev** [comment]
CP: 414 IV: 86.7%
 Level: 24 Monster: ♂Hoothoot
  Catch Probability: ???/???/???

Not getting anything after pulling

**Comment by whitewillem** [comment]
Use PokeAlarm dev branche.

**Comment by The-Real-Ketchum-Dev** [comment]
I am

On Feb 28, 2018 9:20 PM, "whitewillem" <notifications@github.com> wrote:

Use PokeAlarm dev branche.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SenorKarlos/RocketMap/pull/56#issuecomment-369452323>,
or mute the thread

**Comment by rlodev67** [comment]
@The-Real-Ketchum-Dev 
Are you running last version of RM ?
Show me your alarm file of PA

**Pull request merged**
