### PR TITLE
overpy for m2

### PR DESCRIPTION
**Pull request by KartulUdus**
The generally accepted theory on where EX raids appear is OSM data light green parks. 
This PR gives the ability to store which gyms can possibly spawn an EX raid within an area
## Description

* New column in gym table (boolean for park or not)
* New requirement for overpy (pip install -r requirements.txt --upgrade)
* New arg for populating Gym.park

Uses existing geofencing functions
Using a single area geofence is required 

Launch with 
`python runserver.py -exg -gf geofences/yourgeofence.txt`
Parks and other applicable green areas will be pulled within the bounding box of your geofence.
Existing gyms within the geofence will be compared against areas
Will update Gym.park=True if the gym is inside an area

## Motivation and Context

My discord was making CSV files of gyms manually and using tools like overpass-turbo to generate maps with the data.
The query was easy enough to implement with overpy to map directly
## How Has This Been Tested?

Hardly at all, I mostly photoshopped the examples below.
## Screenshots (if appropriate):
screen shot 2018-01-16 at 03 09 25

The switch:
screen shot 2018-01-19 at 00 08 00

Switch when turned off or on:
screen shot 2018-01-19 at 00 27 58
screen shot 2018-01-18 at 23 59 35

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bcrucialhd** [comment]
I saw a monocle branch do this and they used and EX logo for the icon

**Comment by CRAKD** [comment]
Yeah i think we should def incorporate something to differentiate the gyms rather than just adding a slider in the menu. I saw the ex logo too that was cool.

**Comment by TheQL** [comment]
Could use ImageMagick to add something to the gym icon, like for example it is done for "in battle" gyms.

**Comment by KartulUdus** [comment]
Sorry for the delay. 
This got merged to vanilla RM, alas there were many changes between this PR and what was merged. 

As someone has already cherry picked from vanilla, I'm closing this PR, but expect a new one shortly.

**Pull request closed without merging**
