### PR TITLE
[Stock-RM] Cleanup routine and TTH Fix

### PR DESCRIPTION
**Pull request by Grennith**
## Description
Latest PRs merged into stock
Fix TTH count for one-hour spawns. (#2512)
Fix typo in -DCf docs. (#2529)
Database Cleanup (#2281 rework) (#2383)

Basically cleans the DB of old records. RM, so far, just stored every mon ever seen. Databases thus kept growing

## How Has This Been Tested?
Well... Map is running fine with a couple hundred workers. Database is less than 100MB in size.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fallenflash** [comment]
what about for people who like to keep the mons for worldopole and the such?  is it disableable?

**Comment by Grennith** [comment]
Well, check the command line options... Individual switches or just don't use cleanup at all

**Comment by CRAKD** [comment]
Does this cleanup cause db locks like the old one?

**Comment by rlodev67** [comment]
sounds good to me, waiting for test;

**Comment by Grennith** [comment]
Been running it fine the past week. Kept my DB relatively small. Running 3 Maps with a total of 900 workers, MariaDB with file per table

**Comment by whitewillem** [comment]
Running this for a few hours now. Looks good. Will report back in a few days.

**Comment by rlodev67** [comment]
thanks

**Pull request merged**
