### PR TITLE
Colored console

### PR DESCRIPTION
**Pull request by iCornflakes**
## Description
Just colors the errors, warnings, normal text etc.
Found that in an older repo.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Pogodenhelder** [comment]
the last commit broke it i think, 
```
Traceback (most recent call last):
  File "runserver.py", line 23, in <module>
    from pogom.app import Pogom
  File "/home/maestro/RocketMap/pogom/app.py", line 484
    if request.args.get('lurePokemon', 'true') == 'true':
                                                        ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by iCornflakes** [comment]
Reverted it. I didnt know it pushes content right to PR as well when committing to base branch.

**Comment by RedFirebreak** [comment]
Tested, looks beautiful
image

**Comment by Pogodenhelder** [comment]
i tested it and it works great..
although on osx the background is white so that looks meh.. :( but overall its ok.

**Comment by iCornflakes** [comment]
What do you mean with osx?

**Comment by Pogodenhelder** [comment]
there are more operating systems then windhoos ^^ :p  OSX is apple's os for mac :p

**Comment by iCornflakes** [comment]
Oh well I didnt think of that. I thought something RM related.

**Comment by Pogodenhelder** [comment]
no no no :p. terminal in osx has white background.. so thats why i said it.
the PR is fine for me to being merged @rlodev67

**Comment by rlodev67** [comment]
Are you sure ? You will need to move on windows... :P

**Comment by rlodev67** [comment]
Thanks for the PR @iCornflakes

**Pull request merged**
